format = '''
[â”Œ--------------------------------------------------------------------------------------------------->](bold blue)
[â”‚](bold red)$directory
[â””â”€>](bold green) '''
symbol = "ğŸŒ± "
truncation_length = 6
truncation_symbol = ""
# ignore_branches = ["master", "main"]
always_show_remote = false
[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "âœ“"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"
[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "
# [git_state]
# format = '[\($state( $progress_current of $progress_total)\)]($style) '
#cherry_pick = "[ğŸ’ PICKING](bold red)"
# [git_metrics]
# added_style = "bold blue"
# format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
# [nodejs]
# format = "[ node -v ğŸ¤– $version](bold green) "
# ~/.config/starship.toml

# Use custom format
# Wait 10 milliseconds for starship to check files under the current directory.
# scan_timeout = 10

# Disable the blank line at the start of the prompt
# add_newline = false
#
# # Set 'foo' as custom color palette
# palette = 'foo'
#
# # Define custom colors
# [palettes.foo]
# # Overwrite existing color
# blue = '21'
# # Define new color

